# Generated by Django 2.0.1 on 2018-01-18 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_chart_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id',
                                    to='api.Chart'),
        ),
    ]
